version: "3"

services:
  backend:
    image: node:latest
    tty: true
    restart: always
    working_dir: /home/tabletoptracker-backend/app
    command: bash -c "npm install && node bin/www"
    ports:
      - ${BACKEND_PORT}:80
    links:
      - db
    volumes:
      - ./:/home/tabletoptracker-backend

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tabletoptracker
    volumes:
      - ./mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    links:
      - db
