version: "3"

services:
  backend:
    image: node:latest
    tty: true
    restart: unless-stopped
    working_dir: /home/tabletoptracker-backend/app
    command: bash -c "npm install && npm run build && npm start"
    ports:
      - ${BACKEND_PORT}:80
      - ${BACKEND_PORT_DEV}:8081
    links:
      - db
    volumes:
      - ./:/home/tabletoptracker-backend

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: tabletoptracker
    volumes:
      - ./mysql:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 3004:80
    links:
      - db
